name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-26

    steps:
      - name: Download project
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          brew install autoconf automake libtool pkg-config
          brew link libtool
          pip install Cython==3.2.0
          pip install kivy-ios

      - name: Build iOS dependencies
        run: |
          toolchain build python3 kivy

      - name: Prepare application
        run: |
          mkdir -p app
          cp main.py app/main.py

      - name: Create Xcode project
        run: |
          toolchain create MySchedule "$PWD/app"

      - name: Show Xcode project
        run: |
          cd MySchedule-ios
          xcodebuild -list

      - name: Build iOS application
        run: |
          cd MySchedule-ios
          xcodebuild \
            -project MySchedule.xcodeproj \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO

      - name: Find MySchedule.app
        run: |
          echo "Searching for MySchedule.app..."
          find MySchedule-ios -name "MySchedule.app" -type d -print

      - name: Create Payload folder
        run: |
          mkdir -p Payload

          APP_PATH=$(find MySchedule-ios -name "MySchedule.app" -type d | head -n 1)

          if [ -z "$APP_PATH" ]; then
            echo "ERROR: MySchedule.app was not found"
            exit 1
          fi

          echo "Found app:"
          echo "$APP_PATH"

          cp -R "$APP_PATH" Payload/MySchedule.app

      - name: Create IPA
        run: |
          zip -r MySchedule.ipa Payload

      - name: Show IPA
        run: |
          ls -lh MySchedule.ipa

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: MySchedule-IPA
          path: MySchedule.ipa

      - name: Upload APP
        uses: actions/upload-artifact@v4
        with:
          name: MySchedule-APP
          path: Payload/MySchedule.app
```
